<%''GENEL
	text="#FFFFFF"
	top_background="#FFE000"
	background="#333333"
	content_bg="#666666"
	menu_bg="#666666"
	menu_back="#444444"
	menu_color="#444444"
	online_admin="#FFCC00"
	online_editor="#FFCC99"
	forum_bg_1="#3F3F3F"
	forum_bg_2="#494949"
	td_border_color="#000000"
	td_border_color2="#CC0000"
	top_menu_color="#666666"
	top_menu_color_hover="#777777"
	top_menu_border=td_border_color
	TableShadow="BACKGROUND-REPEAT: repeat-x;BORDER-RIGHT: "&top_menu_border&" 1px solid;BACKGROUND-REPEAT: repeat-x;BORDER-BOTTOM: "&top_menu_border&" 1px solid;BACKGROUND-REPEAT: repeat-x;"
	TableBorder="BACKGROUND-REPEAT: repeat-x;BORDER-RIGHT: "&td_border_color2&" 1px solid;BACKGROUND-REPEAT: repeat-x;BORDER-BOTTOM: "&td_border_color2&" 1px solid;BACKGROUND-REPEAT: repeat-x;BORDER-LEFT: "&td_border_color2&" 1px solid;BORDER-TOP: "&td_border_color2&" 1px solid;"
%>